#!/usr/bin/env python
# @author: Prahlad Yeri
# @description: Small daemon to create a wifi hotspot on linux
# @license: MIT
# python -m hotspotd $*
import sys
import os


from hotspotd import main


if __name__ == "__main__":
    # check root or not
    # if os.getenv('USER') != 'root':
    if os.getenv('HOME') != '/root':
        if os.getenv('SUDO_USER') is None:
            sys.exit("You need root permissions to do this, sloth!")

    main()
